# Generated by Django 2.2.5 on 2019-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190918_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='', help_text='留言内容', verbose_name='留言内容'),
        ),
    ]
